-- 문제: 가격이 제일 비싼 식품의 정보 출력하기
-- 답변 1) 서브 쿼리 활용
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) 
               FROM FOOD_PRODUCT);
-- 답변 2) LIMIT 사용
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC LIMIT 1;

-- 문제: 최댓값 구하기
SELECT MAX(DATETIME) FROM ANIMAL_INS;

-- 문제: 최솟값 구하기
SELECT MIN(DATETIME) FROM ANIMAL_INS;

-- 문제: 동물 수 구하기
SELECT COUNT(ANIMAL_ID) FROM ANIMAL_INS;

-- 문제: 중복 제거하기
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

-- 문제: 조건에 맞는 아이템들의 가격의 총합 구하기
SELECT SUM(PRICE) AS TOTAL_PRICE
FROM ITEM_INFO
WHERE RARITY = 'LEGEND';

-- 문제: 잡은 물고기 중 가장 큰 물고기의 길이 구하기
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH
FROM FISH_INFO;